name: guitar2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - tensorflow=2.11
  - numba=0.56.4
  - llvmlite=0.39.1
  - librosa=0.9.2
  - crepe
  - pip
  - pip:
      - ddsp[data_preparation]==1.6.3
      - google-api-core==2.11.0
      - googleapis-common-protos==1.56.2
      - google-cloud-core==2.3.2
      - google-cloud-storage==2.5.0
      - tensorflow-datasets==4.9.2
      - etils==1.5.1
